// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyjfwzifmkqgglmnkfix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5amZ3emlmbWtxZ2dsbW5rZml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjk2OTQsImV4cCI6MjA2NDY0NTY5NH0.jUAgGHuE41KxPL4lR7txjLc-ZZfh2Wal4DItGlCLv24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);